[package]
name = "alti2"
version = "0.1.0"
authors = ["Jake McGinty <me@jake.su>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial = "0.4"
hex = "0.4"
anyhow = "1"
